name: rickymortyCD

on: push

jobs:
  compile:
    name: Compiler
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses:actions/checkout@v2 
      - name: compiler install
        uses:npm install
      - name: build
        uses: npx next build 
      - name: export
        uses: npx next export 
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: compile
    steps:
      - name: deploy to surge rickymortilink.surge.sh
        uses: dswistowski/surge-sh-action@v1
        with:
          domain: 'rickymortylink.surge.sh'
          project: './out'
          login: ${{ secrets.surge_login }}
          token: ${{ secrets.surge_token }}