name: rickymortyCD

on: push

jobs:
  compile:
    name: Compiler
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2 
      - name: compiler install
        run: npm install
      - name: build
        run: npx next build 
      - name: export
        run: npx next export 
      - name: checkout
        uses: actions/checkout@v2 
      - name: deploy to surge rickymortilink.surge.sh
        uses: dswistowski/surge-sh-action@v1
        with:
          domain: 'rickymortylink.surge.sh'
          project: './out'
          login: ${{ secrets.surge_login }}
          token: ${{ secrets.surge_token }}